In [1]:
import numpy as np
import numpy.linalg as lin #linear algebrea

In [2]:
a = np.array([[1, 1], [2, 1]])
print(a)
print(a.shape)

a_ = lin.inv(a)
print(a_)

y = np.array([2, 4]) #얘는 벡터

[[1 1]
 [2 1]]
(2, 2)
[[-1.  1.]
 [ 2. -1.]]


In [3]:
#여기서 w는 기울기와 y절편을 구하는것, y는 행렬이 아니다. rank, 즉 1차원 벡터이다. 행렬은 행렬로 바꾸어야 한다. 그게 나중에
#문제를 방지해준다. 따라서, 다음과 같이 정의하는게 좋다. 자동적으로, 변환해 주기는 하지만(브로드캐스팅),
#1*2 -> 2*1꼴로 바꾸어 주어야한다. 

y_1 = np.array([[2, 4]]) #얘는 행렬
print(y.shape) #행렬이 아니라, 벡터
print(y_1.shape)
y_2 = np.array([[2], [4]]) #우리가 원했던, 2*1꼴이 나온다.
print(y_2.shape)

#이런 방식도 있다.
y = np.array([2, 4]).reshape(2,1)
print(y)

#산술곱
w = a_ * y
print(w)

#행렬곱
w = np.matmul(a_, y)
print(w)

#()는 벡터, []은 행렬

(2,)
(1, 2)
(2, 1)
[[2]
 [4]]
[[-2.  2.]
 [ 8. -4.]]
[[2.]
 [0.]]


In [4]:
a = np.array([[1, 1], [2, 1], [3, 1]])
a_ = lin.pinv(a)
print(a_)

y = np.array([2, 4, 6.4]).reshape(3, 1)
w = np.matmul(a_, y)
print(w)

#(1, 2), (2, 4), (3, 6.4)를 다 꿰뚫는 선은 존재하지 않는다. 그러나, 우리의 목적이 -무한대에서 무한대까지 모두 나타낼 수 있는 값(선)을
#찾는것

#x가 1일때, y값 얼마인지
#기울기 2.2, y절편 -0.266666667

[[-5.00000000e-01 -3.19189120e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]
[[ 2.2       ]
 [-0.26666667]]


In [5]:
#x가 1일 때, y가 얼마인지를 보여주는 코드
#y = w*x +b, 단순하고, 직관적인 방법
y = w[0, 0] * 1 + w[1, 0]
print(y)

#근사값이 나온다. 다 오차가 존재한다.
#하지만, 이렇게 되면, 테스트하기 힘들어진다.

x = np.arange(-10, 10)
y = w[0, 0]*x + w[1, 0]

print(w[0][0])
print(y)

#np. matmul(w, np.array([1, 1]))

1.9333333333333322
2.2000000000000006
[-22.26666667 -20.06666667 -17.86666667 -15.66666667 -13.46666667
 -11.26666667  -9.06666667  -6.86666667  -4.66666667  -2.46666667
  -0.26666667   1.93333333   4.13333333   6.33333333   8.53333333
  10.73333333  12.93333333  15.13333333  17.33333333  19.53333333]


In [9]:
#numpy의 가장 기본적인 개념은 다차원 배열이라는것, 고속으로 계산 가능, 몇백배 차이가 난다.
#파이썬은 인터프리터 언어라, for문을 사용하면 느리지만, numpy는 하나의 타입만을 다루며(문자, 숫자 섞어서 안쓴다.) c로 구현되어 있어
#빠르다.

#2행렬로 바꿔놓으면, 계산이 정말 빠르게 된다.

a = np.array([[2, 2, 0], [-2, 1, 1]])
lin.inv(a)

a = np.array([[1, 2], [2, 4], [3, 6.4]])
print(np.lin.pinv(a))

LinAlgError: Last 2 dimensions of the array must be square